version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/maven-demo
    steps:
      - checkout
      - run: mvn verify -f build-helper-maven-plugin/pom.xml
      - run: mvn verify -f maven-compiler-plugin/pom.xml
